In [1]:
import numpy as np


## Numpy indexing and slicing of vectors

In [2]:
arr = np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[1:5] #starting ending 
arr[:5]
arr[:]
arr[3:]
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [11]:
# Numpy indexing and slicing of matrix : 

arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
# arr[0] this will target rows indexin
# arr[1]
# arr[2]
# arr[3]
# arr[4]
# arr[5]
# arr[0:,1]
# arr[5,4]
# arr[4,2]
# arr[3,2]
# arr[3,3]
# arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [26]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [30]:
# arr[3:,3:]
# arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [33]:
# Boolean indexing :

arr = np.arange(11,21)
bool_index = arr%2 == 0 
bool_index


array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [34]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])