list = [1,2,3,4]
array = [1,2,3,4]


Numpy Arrays : 


when we were doing python we had the data structure list and numpy is famous for arrays.



numpy arrays : 

Basic array creation 
array generation function
random generation function
array attributes
array methods

reshaping and resizing




In [2]:
import numpy as np


In [3]:
#Basic array creation 

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
a = [1,2,3,"hello"]
a

[1, 2, 3, 'hello']

# arrays : same data type hunu parxa 
np.array(a)
<u21 = unicode mah change vayo  ya string ma convert vayo vanay ko 

In [10]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array generation function


In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
# genrate some zeroes
# arr = np.zeros(6)
# arr
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
# linspace
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [56]:
# Random generation function : 

# random allows us to generate some random numbers  and np allows sus to create
# some array

# numpy install garyo vanay random pani atomatically install hunxa 
# rand, standarlization mah -3 +3 sama ko sabai value awaxa 


np.random.rand(10)
np.random.randn(10)
np.random.randint(6) #0 dekhi 6 ko bich ko elements dinxa
np.random.randint(10,20,10) #10 deki 10 saama 10 euta elements

array([11, 12, 15, 12, 13, 14, 19, 11, 14, 12], dtype=int32)

# array attributes
<!-- 
attributes are kind of variable definedd inside the class and 
methods are function defined inside class


attributes lai call gardaina methods lai call garxa -->

In [57]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
# shape kati euta rows ra columns xa vanxa
# shape is attributes
# size elements
# arr.dtype
arr.shape
arr.size
arr.dtype

dtype('int64')

In [73]:
# array methods a
arr.min()
arr.max()
arr.sum()
# perrow ra column ko sum 0 == column 1 == row

arr
np.sum(arr,axis = 0)
np.sum(arr,axis = 1)
arr.mean()
arr.std()
arr.argmax()
arr.argmin()


np.int64(0)

In [77]:
# reshaping and resizing 
# i want to reshap and resizing 
arr = np.arange(1,31)
arr = arr.reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])