arithmetic operations


broadcasting 


deep and shallow copy 

matrix operations


advance array manipulation 


stacking array 


splitting array

In [1]:
import numpy as np


In [9]:
# arithmetic operations
# size most be same in both elements 
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [10]:
# a3 = a1+a2
# a3

array([ 7,  9, 11, 13, 15])

In [11]:
# a3 = a1*a2
# a3

array([ 6, 14, 24, 36, 50])

In [13]:
a4 = a1-a2
a4

array([-5, -5, -5, -5, -5])

In [15]:
aa = a1/a2
aa

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [16]:
aab = a1%a2
aab

array([1, 2, 3, 4, 5])

In [21]:
# Broadcasting : 
# ma sanga elements haru tanai ra tyo sabai elements mah mailay 10 add garna 
# khojay vanay that called broadcasting

arr2 = aab+10

array([11, 12, 13, 14, 15])

In [29]:
arr2 = np.arange(1,26).reshape(5,5)
arr = arr2 +10

In [30]:
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [22]:
# deep and shallow copy 

In [36]:
a = np.arange(1,21)
a
slice = a[0:5]
slice= slice*10
slice
a
# shallow copy : change hudaina
# b ko mah change garya ko a ko mah change na hos vanay 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
# main array mah change hunxa  deep copy mah 
a[4:6]*10
a
b = a
b[0]= 99
b
a


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
# matrix operation : 
# DOTPRODUCT
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [51]:
A

array([[1, 2],
       [3, 4]])

In [52]:
B

array([[5, 6],
       [7, 8]])

In [53]:
A@B

array([[19, 22],
       [43, 50]])

In [54]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [55]:
# Transpose matrix: row become colume

In [57]:
A.T

array([[1, 3],
       [2, 4]])

In [64]:
# STACKING ARRAY 


# jodinay  two  matrix lai stacking garna mildaina two arrays lai garna milxa
# two vectors lai garna milxa


# vertical , horizontal , simple stack 
a= np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([7,8,9,10])
# np.vstack((a,b))
# np.hstack((a,b))   #duta array lai sangai rakhdeyo


# column stack 
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [65]:
# splitting array 

c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
# np.hsplit(c,2) division jastai ho kya
a = np.vsplit(c,4)
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
