In [3]:
import numpy as np
s = np.array([
        [5, 3, 4, 6, 7, 8, 9, 1, 2],
        [6, 7, 2, 1, 9, 5, 3, 4, 8],
        [1, 9, 8, 3, 4, 2, 5, 6, 7],
        
        [8, 5, 9, 7, 6, 1, 4, 2, 3],
        [4, 2, 6, 8, 5, 3, 7, 9, 1],
        [7, 1, 3, 9, 2, 4, 8, 5, 6],
        
        [9, 6, 1, 5, 3, 7, 2, 8, 4],
        [2, 8, 7, 4, 1, 9, 6, 3, 5],
        [3, 4, 5, 2, 8, 6, 1, 7, 9]
    ])

In [15]:
# sum of each and every row
b = np.sum(s,axis = 1)
# b == 45
for i in b:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("FOr rows it is valid")

FOr rows it is valid


In [16]:
c = np.sum(s,axis = 1)
# b == 45
for i in c:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("FOr rows it is valid")

FOr rows it is valid


In [26]:
s
# s[0:3,0:3]
# s[0:3 , 3:6]
# s[0:3,  6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [28]:
# s[3:6,0:3]
# s

In [30]:
for i in range(0,8,3):
    for j in range(0,9,3):
        
        n = (s[i:i+3,j:j+3])
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [69]:
import numpy as np
# Columns: [Age, Math Marks, Science Marks],
data = np.array([
       [18, 85, 78],   
       [19, 92, 88],   
        [17, 76, 95],  
        [18, 65, 70],   
        [20, 90, 85]    
    ])
   

In [33]:
# get the shape of the matrix
data.shape

(5, 3)

In [38]:
# find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [39]:
# extract math marks of all students 
data[:,1]

array([85, 92, 76, 65, 90])

In [64]:
# find the highest science marks.
np.max(data[:,2])

np.int64(95)

In [55]:
# get details of the students who scored more than 90 in maths
# indexing in boolen



data[data[:,1]>90]

array([[ 18,  95,  78],
       [ 19, 102,  88],
       [ 20, 100,  85]])

In [71]:
# increase maths marks of all students by 5
data[:,1]+=5

data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [78]:
# find how many students are younger than 19
len(data[data[:,0]<19])

3

In [83]:
# calculate the average marks in each subject
# np.mean(data[:,1:],axis= 0)

array([86.6, 83.2])

In [85]:
# get data of students who scored atleast 80 in both subject: 
data[(data[:,1]>=80)& (data[:,2]>= 80)]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [93]:
# Replace all science marks<75 with 0.
data[:,2][data[:,2]< 75]= 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [ 0,  0,  0],
       [20, 95, 85]])